### ISSUE TITLE
issue in zh-CN.yml

### ISSUE THREAD

**Issue by moonavw** [tigrish/kaminari-i18n#23]
this line:
display_entries: "显示 %{entry_name} <b>%{first} - %{last}</b>  共<b>%{total}</b> 页"

should be:
display_entries: "显示 %{entry_name} <b>%{first} - %{last}</b>  共<b>%{total}</b>"

that is total count , not total page.

**Comment by tigrish** [comment]
Pull requests welcome!

**Comment by lingceng** [comment]
@moonavw  
The %{entry_name} will be appending with 's'. 
It generates something like "显示 订单s 1-20 共30"

So the `%{entry_name}` should be removed too. Here is my version:
```
  helpers:
    page_entries_info:
      more_pages:
        display_entries: "显示 <b>%{first} - %{last}</b>条  共<b>%{total}</b> 条记录"
      one_page:
        display_entries: "显示 <b>所有 %{count}</b> 条记录"
```
